import { DataMode, RecoveryOption } from "@ezykwelez/shared";

export interface SimulationScenario {
  id: string;
  name: string;
  description: string;
  disruptionType: string;
  durationHours: number;
  expectedLoadFactor: number;
  availableBackupPower: boolean;
  activeContingencies: string[];
}

export interface SimulationResult {
  scenarioId: string;
  disruptionScore: number;
  estimatedDisplacedStudents: number;
  bottleneckFacilities: string[];
  recommendedRecoveryOption: string;
  dataMode: DataMode;
  simulatedAt: string;
  notes: string[];
}

export interface RecoveryOptionSimulationResult {
  optionId: string;
  optionTitle: string;
  planId?: string;
  incidentId?: string;
  dataMode: DataMode;
  simulatedAt: string;
  before: {
    disruptedNodes: number;
    disruptedLocations: number;
    displacedStudents: number;
    severityScore: number;
  };
  after: {
    disruptedNodes: number;
    disruptedLocations: number;
    displacedStudents: number;
    severityScore: number;
  };
  delta: {
    impactPercentReduction: number;
    restoredStudents: number;
    restoredLocations: number;
    estimatedTimeToRestore: string;
  };
  rationale: string;
  keyTradeoff: string;
  notes: string[];
}

export const simulationService = {
  async getPresetScenarios(): Promise<SimulationScenario[]> {
    return [
      {
        id: "scen-grid-b-overheat",
        name: "Power Substation Grid B Peak Overload",
        description: "Simulates full transformer trip during maximum Monday morning class hours.",
        disruptionType: "power_outage",
        durationHours: 3.5,
        expectedLoadFactor: 1.2,
        availableBackupPower: true,
        activeContingencies: ["Automatic Generator Start", "Load Shedding Block C"],
      },
      {
        id: "scen-campus-wifi-core",
        name: "Core Campus Wi-Fi Switch Failure",
        description: "Simulates optical transceiver failure disconnecting Central Library & Seminar Halls.",
        disruptionType: "network_outage",
        durationHours: 1.5,
        expectedLoadFactor: 0.9,
        availableBackupPower: true,
        activeContingencies: ["LTE Hotspot Failover", "Offline LMS Cache"],
      },
      {
        id: "scen-chiller-fault",
        name: "Block C HVAC Chiller Breakdown",
        description: "Simulates thermal overload in Computer Labs during heatwave.",
        disruptionType: "equipment_failure",
        durationHours: 5.0,
        expectedLoadFactor: 1.0,
        availableBackupPower: false,
        activeContingencies: ["Lab Rotation Schedule"],
      },
    ];
  },

  async runSimulation(scenario: SimulationScenario): Promise<SimulationResult> {
    return {
      scenarioId: scenario.id,
      disruptionScore: scenario.durationHours * scenario.expectedLoadFactor * 42.5,
      estimatedDisplacedStudents: Math.round(180 * scenario.expectedLoadFactor),
      bottleneckFacilities: ["Central Library (Floor 2)", "Physics Practicum Lab B201"],
      recommendedRecoveryOption: scenario.availableBackupPower
        ? "Failover to Substation Feeder Ring A (Backup)"
        : "Relocate PHYS-101 Practicum to Seminar Hall C204",
      dataMode: DataMode.SIMULATED,
      simulatedAt: new Date().toISOString(),
      notes: [
        "SIMULATED DRILL: Results generated by local counterfactual calculation engine.",
        "Zero real-world infrastructure altered.",
      ],
    };
  },

  async simulateRecoveryOption(
    option: RecoveryOption,
    context?: {
      planId?: string;
      incidentId?: string;
      baselineDisruptedNodes?: number;
      baselineDisruptedLocations?: number;
      baselineDisplacedStudents?: number;
    }
  ): Promise<RecoveryOptionSimulationResult> {
    const baseNodes = context?.baselineDisruptedNodes ?? 3;
    const baseLocs = context?.baselineDisruptedLocations ?? 2;
    const baseStudents = context?.baselineDisplacedStudents ?? 120;
    const baseScore = 85.0;

    const percentRed = option.estimatedImpactReduction.estimatedPercent ?? 75.0;
    const nodeRed = option.estimatedImpactReduction.affectedNodeReduction ?? 2;
    const locRed = option.estimatedImpactReduction.affectedLocationReduction ?? 1;

    const afterNodes = Math.max(0, baseNodes - nodeRed);
    const afterLocs = Math.max(0, baseLocs - locRed);
    const afterStudents = Math.round(baseStudents * (1 - percentRed / 100));
    const afterScore = Math.max(0, Number((baseScore * (1 - percentRed / 100)).toFixed(1)));

    const tradeoff = option.tradeoffs && option.tradeoffs.length > 0
      ? `${option.tradeoffs[0].dimension}: ${option.tradeoffs[0].value} (${option.tradeoffs[0].explanation})`
      : "Standard operational resource reallocation required.";

    const restoreTime = `${option.estimatedRecoveryTime.value} ${option.estimatedRecoveryTime.unit}`;

    return {
      optionId: option.id,
      optionTitle: option.title,
      planId: context?.planId,
      incidentId: context?.incidentId,
      dataMode: DataMode.SIMULATED,
      simulatedAt: new Date().toISOString(),
      before: {
        disruptedNodes: baseNodes,
        disruptedLocations: baseLocs,
        displacedStudents: baseStudents,
        severityScore: baseScore,
      },
      after: {
        disruptedNodes: afterNodes,
        disruptedLocations: afterLocs,
        displacedStudents: afterStudents,
        severityScore: afterScore,
      },
      delta: {
        impactPercentReduction: percentRed,
        restoredStudents: baseStudents - afterStudents,
        restoredLocations: baseLocs - afterLocs,
        estimatedTimeToRestore: restoreTime,
      },
      rationale: option.rationale || "Calculated candidate strategy to mitigate student delay.",
      keyTradeoff: tradeoff,
      notes: [
        `Verified constraint satisfaction: ${option.feasibility.toUpperCase()}`,
        `Confidence Level: ${option.confidence.toUpperCase()}`,
        "Counterfactual evaluation derived from real recovery option parameters.",
      ],
    };
  },
};

export const simulateRecoveryOption = simulationService.simulateRecoveryOption;
