import { DataMode } from "@ezykwelez/shared";

export interface SimulationScenario {
  id: string;
  name: string;
  description: string;
  disruptionType: string;
  durationHours: number;
  expectedLoadFactor: number;
  availableBackupPower: boolean;
  activeContingencies: string[];
}

export interface SimulationResult {
  scenarioId: string;
  disruptionScore: number;
  estimatedDisplacedStudents: number;
  bottleneckFacilities: string[];
  recommendedRecoveryOption: string;
  dataMode: DataMode;
  simulatedAt: string;
  notes: string[];
}

export const simulationService = {
  async getPresetScenarios(): Promise<SimulationScenario[]> {
    return [
      {
        id: "scen-grid-b-overheat",
        name: "Power Substation Grid B Peak Overload",
        description: "Simulates full transformer trip during maximum Monday morning class hours.",
        disruptionType: "power_outage",
        durationHours: 3.5,
        expectedLoadFactor: 1.2,
        availableBackupPower: true,
        activeContingencies: ["Automatic Generator Start", "Load Shedding Block C"],
      },
      {
        id: "scen-campus-wifi-core",
        name: "Core Campus Wi-Fi Switch Failure",
        description: "Simulates optical transceiver failure disconnecting Central Library & Seminar Halls.",
        disruptionType: "network_outage",
        durationHours: 1.5,
        expectedLoadFactor: 0.9,
        availableBackupPower: true,
        activeContingencies: ["LTE Hotspot Failover", "Offline LMS Cache"],
      },
      {
        id: "scen-chiller-fault",
        name: "Block C HVAC Chiller Breakdown",
        description: "Simulates thermal overload in Computer Labs during heatwave.",
        disruptionType: "equipment_failure",
        durationHours: 5.0,
        expectedLoadFactor: 1.0,
        availableBackupPower: false,
        activeContingencies: ["Lab Rotation Schedule"],
      },
    ];
  },

  async runSimulation(scenario: SimulationScenario): Promise<SimulationResult> {
    // Deterministic simulation output clearly labeled as simulated data
    return {
      scenarioId: scenario.id,
      disruptionScore: scenario.durationHours * scenario.expectedLoadFactor * 42.5,
      estimatedDisplacedStudents: Math.round(180 * scenario.expectedLoadFactor),
      bottleneckFacilities: ["Central Library (Floor 2)", "Physics Practicum Lab B201"],
      recommendedRecoveryOption: scenario.availableBackupPower
        ? "Failover to Substation Feeder Ring A (Backup)"
        : "Relocate PHYS-101 Practicum to Seminar Hall C204",
      dataMode: DataMode.SIMULATED,
      simulatedAt: new Date().toISOString(),
      notes: [
        "SIMULATED DRILL: Results generated by local counterfactual calculation engine.",
        "Zero real-world infrastructure altered.",
      ],
    };
  },
};
